package goofer

import "github.com/gooferOrm/goofer/schema"

type PostRepository interface {
    Create(entity *Post) error
    FindByID(id int64) (*Post, error)
}

// PostRepo is the concrete implementation of PostRepository
// This will be generated by the engine
var _ PostRepository = (*PostRepo)(nil)

type PostRepo struct {
    schema.Entity
}

func (r *PostRepo) Create(entity *Post) error {
    return nil // Implementation will be generated by the engine
}

func (r *PostRepo) FindByID(id int64) (*Post, error) {
    return nil, nil // Implementation will be generated by the engine
}
