package goofer

import "github.com/gooferOrm/goofer/schema"

type UserRepository interface {
    Create(entity *User) error
    FindByID(id int64) (*User, error)
}

// UserRepo is the concrete implementation of UserRepository
// This will be generated by the engine
var _ UserRepository = (*UserRepo)(nil)

type UserRepo struct {
    schema.Entity
}

func (r *UserRepo) Create(entity *User) error {
    return nil // Implementation will be generated by the engine
}

func (r *UserRepo) FindByID(id int64) (*User, error) {
    return nil, nil // Implementation will be generated by the engine
}
